### PR TITLE
various Fixes

### PR DESCRIPTION
**Pull request by SimonFischer04**
This PR includes various fixes / improvements:
- updates dependencies
- migrates from nopy to autopy
    -  now uses a python venv. Fixes https://github.com/DrozmotiX/ioBroker.esphome/issues/158, Fixes https://github.com/DrozmotiX/ioBroker.esphome/issues/164
    - automatically downloads / installs python
        -  python is removed as a Prerequisite in readme / no need to specify python.execPath in package.json. Fixes https://github.com/DrozmotiX/ioBroker.esphome/issues/163
        - Could fix https://github.com/DrozmotiX/ioBroker.esphome/issues/138
        - Could fix https://github.com/DrozmotiX/ioBroker.esphome/issues/135
        - Could fix https://github.com/DrozmotiX/ioBroker.esphome/issues/120
- migrate to @2colors/esphome-native-api (seems to be the (currently) most maintained one:
    - newer message types defined. Fixes https://github.com/DrozmotiX/ioBroker.esphome/issues/165, Fixes https://github.com/DrozmotiX/ioBroker.esphome/issues/147
    - implementing number type handling. Fixes https://github.com/DrozmotiX/ioBroker.esphome/issues/136, Fixes https://github.com/DrozmotiX/ioBroker.esphome/issues/132
    - implements button type: Fixes https://github.com/DrozmotiX/ioBroker.esphome/issues/124, Fixes https://github.com/DrozmotiX/ioBroker.esphome/issues/127, Fixes https://github.com/DrozmotiX/ioBroker.esphome/issues/134
- Fix for #148
- adds devcontainer
- implements https://github.com/ioBroker/create-adapter/blob/master/docs/updates/20220908_fix_lint_command.md

### CODE REVIEW

**Comment by SimonFischer04** [comment]
@DutchmanNL would you mind taking a look?

**Comment by DutchmanNL** [comment]
> @DutchmanNL would you mind taking a look?

thank you remaindering me, WoW !!! Awesome dude, you ROCK !
I was planning to take this one up (integration of the new API) but didn't had the time yet and just noticed your amazing PR which fully blowed me away!

I will review and test it this week but it looks already awesome and safes me a lot of stuff on my side

Are you reachable on discord or Telegram to discuss if any questions occur or should we keep it here

**Comment by SimonFischer04** [comment]
I'm technically open to dicussing on telegram / discord. 
But why not keep it here, so it's also visible for others / documented here and easier to directly comment on specific changes if required, .... ?

**Review by DutchmanNL — APPROVED** [review]

**Comment by SimonFischer04** [comment]
Thanks for reviewing and merging. Please create a new release also.

**Comment by DutchmanNL** [comment]
> Thanks for reviewing and merging. Please create a new release also.

Thank you for your input, appreciated!

I didn't see any strange thinks and indeed solution you made with separate state creation fits design of the structure.

Running some test now at my home installation and would like to solve the spam errors if a device disconnects and than I will release a new version to NPM

I expect that will be somewhere end of the week.

Is it ok for you if I include your name for the fixes into the readme ? You deserve the credits!!

**Comment by DutchmanNL** [comment]
@SimonFischer04 hmm looks like we have an issue, at least on my side. The ESPHome dashboard proces is not working anymore, did you encounter any issues with that ?

**Comment by DutchmanNL** [comment]
Screenshot 2023-10-18 at 15 38 53

**Comment by SimonFischer04** [comment]
> I expect that will be somewhere end of the week.

No problem. Just thought (and was also bit surprised you supposedly did so quick) you already tested as you already merged. Would have been also possibly to test by directly installing the adapter from my branch in iobroker.

**Comment by SimonFischer04** [comment]
> Is it ok for you if I include your name for the fixes into the readme ? You deserve the credits!!

Yes, would be pleased.

**Comment by SimonFischer04** [comment]
> Screenshot 2023-10-18 at 15 38 53

as for one of this logs see: https://github.com/DrozmotiX/ioBroker.esphome/pull/170 :)

other than that just tested (as already before) again using the direct install from url feature on my test-vm using the new changes on main branch here and dashboard works for me.
Worth to mention that I also still sometimes get this log entry. Debugging it, it seems like just a line-break. I didn't change anything about this logging logic here. I don't know why something (only a empty newline) is getting logged here. I think this can be just filtered out?:
image

Do you mean that it actually **does not work** for you or just the log-entry?

**Comment by DutchmanNL** [comment]
> Do you mean that it actually **does not work** for you or just the log-entry?

It was not working for me at all anymore (Adapter yes but dashboard not)
Did setup 4 new environments and was not able to reproduce it at all for now except my own installation

will deep dive a little more into it and try to reproduce. Maybe it’s indeed just my installation for some reason

**Comment by SimonFischer04** [comment]
> Did setup 4 new environments and was not able to reproduce it at all for now except my own installation

so you just get a 404 when trying to access the dashboard on you own installation?

**Pull request merged**
