### PR TITLE
fix change light state

### PR DESCRIPTION
**Pull request by Jey-Cee**
state was not updated in deviceInfo JSON.
Also do no longer send not supported values.

### CODE REVIEW

**Comment by Jey-Cee** [comment]
Please wait with merge, have to check while effects are not working.

**Comment by DutchmanNL** [comment]
> Please wait with merge, have to check while effects are not working.

Did you manage to have a look at it ? I making a new release now to fix previous bugs

**Comment by Jey-Cee** [comment]
Nope, sorry

**Comment by msapogov** [comment]
> > Please wait with merge, have to check while effects are not working.
> 
> Did you manage to have a look at it ? I making a new release now to fix previous bugs

Jey-Cee:patch-1

Light State wel working

State ON/OFF - working
Brightness - working
colorTemperature - working

**Pull request merged**
