### PR TITLE
Device Type Select

### LINKED ISSUE #169: Adding Type "Select" to ESP Home Adapter
Beca or Koenighaus thermostats with Tuya Protocol send a datapoint from type ENUM. This datapoint has these values: 0: Manual, 1: Schedule and on Koenighaus 2: Holiday.

```
select:
  # Mode
  - platform: "tuya"
    #name: Schedules
    internal: true
    id: mode
    icon: "mdi:calendar"
    enum_datapoint: 4
    options:
      0: Manual
      1: Schedule
      2: Holiday -> only for Koenighaus
    on_value:
        - script.execute: switching
```

@DutchmanNL : Is there an opinion to integrate the select mode in the ESP Home Adapter?

Many thanks for supporting.

### PR DESCRIPTION
**Pull request by SimonFischer04**
- add select device type. Fixes #169 
- comment out unused and non-standard common.modify

Waiting for original poster feedback in #169 - therefore draft for now.

### CODE REVIEW

**Review by DutchmanNL — APPROVED** [review]
nicely solved and code wel understood respect! Indeed very good, as information select menu is already available in API data, to use that directly to generate a dropdown instead of stateAttr entry.

thank you

**Comment by DutchmanNL** [comment]
thank you! Lets wait for feedback from @patricknitsch before merging :)

**Comment by DutchmanNL** [comment]
@SimonFischer04 ready to be merged or would you like to test/update some additional stuff?

**Comment by SimonFischer04** [comment]
> @SimonFischer04 ready to be merged or would you like to test/update some additional stuff?

no i already tested myself. just wanted to make sure it works for / get feedback from  @patricknitsch

**Comment by SimonFischer04** [comment]
> nstead of stateAttr entry

yes, already used that to implement button. but doesn't help here before the info is dynamic.

**Comment by DutchmanNL** [comment]
Merged as we got confirmation 

I will make a new release end of the day

If time allows I will also include a first go for cleanup of offline devices we discussed in the other issue.

Based on that we can continue for channels & states

Will create a new Branche for that but first some go-karting with my children 😅

**Pull request merged**
